# Copyright 2025-2026 .chance (dotchance)
# Licensed under the Apache License, Version 2.0. See LICENSE file.

"""Policy dataclasses shared by the loader, manager, daemon, and observer.

These classes intentionally stay plain. They are the normalized in-memory
representation between "human YAML" and "packed bytes written into eBPF maps."
As Rudder grows toward a richer grammar, that grammar should still compile into
objects with the same kind of explicit fields.
"""

from dataclasses import dataclass, field
from ipaddress import IPv4Address, IPv4Network
from typing import Optional

MAX_RULES = 64
MAX_TARGETS = 12


@dataclass
class MatchSet:
    """Packet fields used to decide whether a rule applies."""

    interface: str                        # interface name or "any"
    src_ip: Optional[IPv4Network] = None
    dst_ip: Optional[IPv4Network] = None
    dscp: Optional[int] = None            # 0-63
    ip_proto: str = "any"                 # "any", "tcp", "udp"


@dataclass
class SteerAction:
    """Action for one-to-one destination rewrite and redirect."""

    dst_ip: IPv4Address
    via: str
    next_hop_mac: Optional[str] = None    # "aa:bb:cc:dd:ee:ff" format


@dataclass
class ReplicationTarget:
    """One unicast output generated by a replicate rule."""

    dst_ip: IPv4Address
    via: str
    next_hop_mac: Optional[str] = None


@dataclass
class ReplicateAction:
    """Action for multicast-to-many-unicast replication."""

    targets: list[ReplicationTarget] = field(default_factory=list)


@dataclass
class Rule:
    """A validated policy rule with an eBPF map slot assignment."""

    name: str
    priority: int
    rule_id: int                          # Slot index assigned by loader: 0..N-1
    type: str                             # "steer" or "replicate"
    match: MatchSet
    action: SteerAction | ReplicateAction
    source_file: str                      # YAML file this rule came from
