# Copyright 2025-2026 .chance (dotchance)
# Licensed under the Apache License, Version 2.0. See LICENSE file.

blank_issues_enabled: true
contact_links:
  - name: Security vulnerability report
    url: https://github.com/dotchance/rudder/security/advisories/new
    about: Please report vulnerabilities privately with a GitHub security advisory.
